spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://127.0.0.1:3306/security-demo

  session:
    store-type: none


security:
  basic:
    enabled: false



